/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.springframework.boot") version "3.1.4"
    id("io.spring.dependency-management") version "1.1.2"
    kotlin("jvm") version "2.0.0"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("jakarta.validation:jakarta.validation-api:3.0.2")
    implementation("org.hibernate:hibernate-validator:8.0.0.Final")

    // Lombok
    compileOnly("org.projectlombok:lombok:1.18.34")
    annotationProcessor("org.projectlombok:lombok:1.18.34")
    implementation(kotlin("stdlib-jdk8"))
}

application {
    mainClass = "org.example.app.App"
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}
